services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=LibreriaBD'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=Marshmello12'
      - 'MARIADB_USER=myuser'
    ports:
      - '40000:40000'  # Puerto 3307 para el acceso desde el host, 3306 es el puerto interno del contenedor
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:                       
    driver: bridge
