services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=LibreriaBD'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=Marshmello12'
      - 'MARIADB_USER=myuser'
    ports:
      - '6000:3306'  # Mapea el puerto 3306 del contenedor al 6000 de la máquina
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:                       
    driver: bridge
