version: '3.8'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=LibreriaBD'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=Marshmello12'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:                      
    driver: bridge
